### ISSUE TITLE
Can't learn new Mortiz Devices

### ISSUE THREAD

**Issue by 9Mad-Max5** [ioBroker/ioBroker.cul#16]
**Describe the bug**  
After pressing the paring button on the MAX Heating Thremostat the adapter just breaks with the attached error log.

**Screenshots & Logfiles**  
`
host.iobroker | 2020-08-11 11:16:56.155 | info | instance system.adapter.cul.0 started with pid 2644
-- | -- | -- | --
host.iobroker | 2020-08-11 11:16:26.077 | info | Restart adapter system.adapter.cul.0 because enabled
host.iobroker | 2020-08-11 11:16:26.076 | info | instance system.adapter.cul.0 terminated with code 0 (NO_ERROR)
host.iobroker | 2020-08-11 11:16:26.075 | error | Caught by controller[1]: at ReadLineParser.Transform._read (_stream_transform.js:191:10)
host.iobroker | 2020-08-11 11:16:26.075 | error | Caught by controller[1]: at ReadLineParser._transform (/opt/iobroker/node_modules/cul/node_modules/@serialport/parser-delimiter/lib/index.js:35:12)
host.iobroker | 2020-08-11 11:16:26.074 | error | Caught by controller[1]: at ReadLineParser.Transform.push (_stream_transform.js:152:32)
host.iobroker | 2020-08-11 11:16:26.074 | error | Caught by controller[1]: at ReadLineParser.Readable.push (_stream_readable.js:212:10)
host.iobroker | 2020-08-11 11:16:26.073 | error | Caught by controller[1]: at readableAddChunk (_stream_readable.js:267:11)
host.iobroker | 2020-08-11 11:16:26.073 | error | Caught by controller[1]: at addChunk (_stream_readable.js:295:12)
host.iobroker | 2020-08-11 11:16:26.072 | error | Caught by controller[1]: at ReadLineParser.EventEmitter.emit (domain.js:483:12)
host.iobroker | 2020-08-11 11:16:26.072 | error | Caught by controller[1]: at ReadLineParser.emit (events.js:315:20)
host.iobroker | 2020-08-11 11:16:26.071 | error | Caught by controller[1]: at ReadLineParser.parse (/opt/iobroker/node_modules/cul/cul.js:320:43)
host.iobroker | 2020-08-11 11:16:26.070 | error | Caught by controller[1]: at Object.module.exports.parse (/opt/iobroker/node_modules/cul/lib/moritz.js:183:51)
host.iobroker | 2020-08-11 11:16:26.069 | error | Caught by controller[1]: TypeError: Cannot read property 'type' of undefined
host.iobroker | 2020-08-11 11:16:26.061 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected
cul.0 | 2020-08-11 11:16:25.497 | info | (2626) Terminated (NO_ERROR): Without reason
cul.0 | 2020-08-11 11:16:25.496 | debug | (2626) Plugin sentry destroyed
cul.0 | 2020-08-11 11:16:25.493 | info | (2626) terminating
cul.0 | 2020-08-11 11:16:25.400 | debug | (2626) ->
cul.0 | 2020-08-11 11:16:25.395 | error | (2626) TypeError: Cannot read property 'type' of undefined at Object.module.exports.parse (/opt/iobroker/node_modules/cul/lib/moritz.js:183:51) at ReadLineParser.parse (/opt/iobroker/node_modu
cul.0 | 2020-08-11 11:16:25.372 | error | (2626) unhandled promise rejection: Cannot read property 'type' of undefined
cul.0 | 2020-08-11 11:16:25.368 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
cul.0 | 2020-08-11 11:15:56.608 | debug | (2626) ->
cul.0 | 2020-08-11 11:15:56.599 | debug | (2626) ->
cul.0 | 2020-08-11 11:15:54.487 | info | (2626) starting. Version 1.3.1 in /opt/iobroker/node_modules/iobroker.cul, node: v12.18.3, js-controller: 3.1.6

`
Versions:

Adapter version: 1.3.1
JS-Controller version: 3.1.6
Node version: v12.18.3
Operating system: Rasbian

**Comment by Apollon77** [comment]
waiting for merge of https://github.com/hobbyquaker/cul/pull/26/files
