### ISSUE TITLE
MAX! Heating thermostat set temperature cannot be set

### ISSUE THREAD

**Issue by luft-post** [ioBroker/ioBroker.cul#38]
**Describe the bug**  
The target temperature cannot be set with the CUNX.
e.g. cul.0.MORITZ.0ad485.desiredTemperature
Version used 1.3.5

**Comment by dieckfr** [comment]
> **Describe the bug**
> The target temperature cannot be set with the CUNX.
> e.g. cul.0.MORITZ.0ad485.desiredTemperature
> Version used 1.3.5

Sag mal, hast Du ne Lösung gefunden?
