### ISSUE TITLE
Control FHT devices

### ISSUE THREAD

**Issue by Lupla** [ioBroker/ioBroker.cul#5]
Hi,
will it be possible to control FHT80b devices?
Greetings from Germany 
Bastian

**Comment by Apollon77** [comment]
Should work: https://github.com/hobbyquaker/cul/blob/master/lib/fht.js

Is it not?

Debug log please.

**Comment by Lupla** [comment]
Pairing is not possible because I cannot set the "Hauscode" in the adapter for the CUNO. But this is essential for pairing.
Without pairing I can only receive signals, but cannot control settings.

**Comment by Apollon77** [comment]
Ahhh now I see. The adapter do not really have implemented controlling of devices at all till now. Basically the used library also supports controlling so it should be doable. 

PRs are also welcome.

**Comment by PG248** [comment]
Want to refresh this post. I've also tried to control some FTH80b thermostats through ioBroker.

Your adapter recognized 4 FHT devices but generated only 4 objects per FHT device after a couple of minutes: addressCode, cmd, cmdRaw, valueRaw. I've hoped I would see the actual and desired temperature as well and could change the desired temperature by writing to this object.

The adapter also recognized one FS20 device with the additional objects adressCodeElv, addressDevice, addressDeviceElv, bidirectional, extended and response.

Any suggestion how I can get/set the desired temperature values from these devices if possible?
