### ISSUE TITLE
Find no way to send FS20 Codes by Objects

### ISSUE THREAD

**Issue by dieckfr** [ioBroker/ioBroker.cul#51]
**Is your feature request related to a problem? Please describe.**

There is no way to send in Objects 

**Describe the solution you'd like**

FS20 Objects for sending Homecode, devicecode, cmd  

**Describe alternatives you've considered**

I spent the hole night the get a solution... I found a lot of questions about this issu, but no solutions

**Additional context**

I hope it is the right way to open an issue :) ??

**Comment by Menne01** [comment]
So ist es auch im MAX! (Moritz) Mode.
Keine Möglichkeit etwas zu senden, geschweige die Thermstaten zu pairen.

Dieser Adapter kann nur empfangen...ohne zu senden absolut unbrauchbar.

LG

Dirk

**Comment by Apollon77** [comment]
Senden ist aktuell testweise für FS20 implementiert, der Rest fehlt ... korrekt. Da müssten User mal genau sagen was Sie brauchen und dann jemand zeit findes es zu machen ... oder besser noch wenn PRs dafür kommen die das implementieren.
