### ISSUE TITLE
Is it possible to set/change the bandwidth?


### ISSUE THREAD

**Issue by Gelbwichtel** [ioBroker/ioBroker.cul#70]
In fhem p.e. is it possible to change the bandwidth for a better receivement in slowrf mode.

In the cul module I find no way to do this.

**Comment by Apollon77** [comment]
Can you provide more details on how to do that?

**Comment by Gelbwichtel** [comment]
Hi,
Danke für deine schnelle Reaktion. Ich schreibe hier mal alles zusammen, was ich zu dem Thema gefunden habe.
Inwieweit das dann zielführend ist, kann ich jetzt nicht abschätzen.

Die Bandbreite soll wohl nur im SLOWRF Modus zum tragen kommen

In FHEM wenn bekomme ich folgende Attribute, wenn ich die Konfiguration des CUL auslese
      ccconf: freq:868.300MHz bWidth:464KHz rAmpl:42dB sens:4dB

Laut CULFW Protokollbeschreibung:

cc1101_bWidth can be set to values between 58 kHz and 812 kHz. Large values are susceptible to interference, but make possible to receive inaccurately calibrated transmitters. It affects tranmission too. Default is 325 kHz.
cc1101_patable change the PA table (power amplification for RF sending)

CUL Protocol Part 2 (radio messages)
CC1100 settings
See the culf/cc1100.h or the official PDF from TI for details.

Change channel bandwidth MDMCFG4 (10). CHANBW_E (bits 7:6), CHANBW_M (bits 5:4)
BWchannel = Fosc/(8 * (4+CHANBW_M) * 2 ^ CHANBW_E)
Example: W1255 (325KHz, default)
W1245 (406KHz)
W1235 (464KHz)

Soweit ich das sehen kann ist W12xy (Achtung Hexwerte) das Kommando an den CUL die Bandbreite zu setzen. xy gibt die Bandbreite vor. Da aber nur die Bits 4-7 verarbeitet werden ist nur das x relevant.

Ergibt in einem Excelsheet folgende mögliche Werte und Frequenzen

![image](https://user-images.githubusercontent.com/71406061/164086434-e30d32f8-083b-4b06-8efd-6566be1ee798.png)

Ich hoffe du kannst damit was anfangen.

**Comment by Gelbwichtel** [comment]
Hallo Inge,

Danke für die rasche Antwort.

Ich werde es mal versuchen, muss mir aber erst wieder einen zusammenlöten.

Die Frage ist nur wie ich das dann testen kann. 

Sag Dir dann Bescheid.

 

cu 

Bodo

 

 

Von: Ingo Fischer ***@***.*** 
Gesendet: Donnerstag, 21. April 2022 15:13
An: ioBroker/ioBroker.cul ***@***.***>
Cc: Gelbwichtel ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.cul] Is it possible to set/change the bandwidth? (Issue #70)

 

Danke, puuhh da muss ich tiefer reinschauen. Da sscheint ja auch nur beim CC1100 zu gehen ... wüste gar nicht wie man den erkennen kann. Also Du kannst ein javascript mal versuchen und dort mit sendTo ne Message zum cul.0 Instanz senden:
message wäre "sendraw" und payload müsste {command: 'Wxxxx'} sein. geht das?

https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#sendto

sendTo('cul.0', 'sendraw', {command: 'Wxxxx'});

**Comment by Gelbwichtel** [comment]
Sorry wegen dem Namen. Handy haltAm 21.04.2022 19:42 schrieb Gelbwichtel ***@***.***>:Hallo Inge,Danke für die rasche Antwort.Ich werde es mal versuchen, muss mir aber erst wieder einen zusammenlöten.Die Frage ist nur wie ich das dann testen kann. Sag Dir dann Bescheid. cu Bodo  Von: Ingo Fischer ***@***.*** Gesendet: Donnerstag, 21. April 2022 15:13An: ioBroker/ioBroker.cul ***@***.***>Cc: Gelbwichtel ***@***.***>; Author ***@***.***>Betreff: Re: [ioBroker/ioBroker.cul] Is it possible to set/change the bandwidth? (Issue #70) Danke, puuhh da muss ich tiefer reinschauen. Da sscheint ja auch nur beim CC1100 zu gehen ... wüste gar nicht wie man den erkennen kann. Also Du kannst ein javascript mal versuchen und dort mit sendTo ne Message zum cul.0 Instanz senden:message wäre "sendraw" und payload müsste {command: 'Wxxxx'} sein. geht das?https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#sendtosendTo('cul.0', 'sendraw', {command: 'Wxxxx'}); —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Gelbwichtel** [comment]
Hallo Ingo,

so, ich hab mal einen Wemos CUL aufgesetzt, dann kann ich über die serielle Schnittstelle noch das Logging sehen. Also, das mit deinem Vorschlag würde funktionieren. Ich sehe, dass die Kommandos rausgehen und am CUL auch ankommen.

Was mir nicht so ganz klar ist, wann der CUL diese Änderungen auch akzeptiert.  Den besten Erfolg hab ich bis data, wen ich es noch einem Neustart des CUL’s mache. Vielleicht muss der CUL auch noch irgendwie in einen bestimmten Modus versetzt werden, damit er die Daten aus dem sendraw auch annnimmt. Aber davon hab ich (noch) keinen Plan. Aber vielleicht sagt Dir das ja etwas.

 

Cu

 

 

 

Von: Ingo Fischer ***@***.*** 
Gesendet: Donnerstag, 21. April 2022 15:13
An: ioBroker/ioBroker.cul ***@***.***>
Cc: Gelbwichtel ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.cul] Is it possible to set/change the bandwidth? (Issue #70)

 

Danke, puuhh da muss ich tiefer reinschauen. Da sscheint ja auch nur beim CC1100 zu gehen ... wüste gar nicht wie man den erkennen kann. Also Du kannst ein javascript mal versuchen und dort mit sendTo ne Message zum cul.0 Instanz senden:
message wäre "sendraw" und payload müsste {command: 'Wxxxx'} sein. geht das?

https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#sendto

sendTo('cul.0', 'sendraw', {command: 'Wxxxx'});

**Comment by Apollon77** [comment]
Ich bin ehrlich: Ich haben keinen CUL und nutze auch den Adapter nicht, von daher ist das ein bissl schwierig zu sagen und recht tief drin. Müsste ich mich einlesen und dann vorauss. raten

**Comment by Gelbwichtel** [comment]
Also ich würde mal sagen, da es ja auf low Level Ebene funktioniert, sollte das auch ausreichen. Der Aufwand wäre eher nicht gerechtfertigt. Ich schließe somit den Thread.
