### ISSUE TITLE
Problems with S300TH sensor address 0

### ISSUE THREAD

**Issue by achimmm** [ioBroker/ioBroker.cul#74]
**Describe the bug**  
Raw data from my S300TH get's received und logged, but no objects are created.
CUL / slowRF / WS Sensors.

**To Reproduce**  
Maybe difficult, but it seems that in main.js, line 331, the code exits although data is received.

**Expected behavior**  
Creation of the objects to show temp and hum.

**Screenshots & Logfiles**  
I just added - for testing purposes - the line "if (obj.address != '0')" and then it worked for me.
Interestingly, obj and obj.protocol have values ...

if (!obj || !obj.protocol || !obj.address) {
   if (obj.address != '0'
      return;
}

**Versions:**  
 - Adapter version: 1.3.5
 - JS-Controller version: latest
 - Operating system: raspbian

**Comment by Apollon77** [comment]
Pleas eprovide more details , your settings and a proper debug log. Thank you.

**Comment by achimmm** [comment]
Here a part of the debug log, where two unknown sensors’s data is retrieved:

2022-05-02 23:34:21.181        info   object cul.0.cul.0.WS.2 created
2022-05-02 23:34:21.167        info   object cul.0.cul.0.WS.2.humidity created
2022-05-02 23:34:21.126        info   object cul.0.cul.0.WS.2.temperature created
2022-05-02 23:34:21.094        debug          RAW: K2122724544, {"protocol":"WS","address":2,"device":"WS300","data":{"temperature":22.2,"humidity":45.7},"rssi":-40}
2022-05-02 23:33:15.269        debug          RAW: K012222502E, {"protocol":"WS","address":0,"device":"S300TH","data":{"temperature":22.2,"humidity":50.2},"rssi":-51}


For the first sensor, no objects get created (Adress 0), but for the other.


Settings of the Adapter:

Serial: /dev/serial/by-id/usb-busware.de_CUL868-if00
Baud: 9600
Mode: SlowRF
Typ: CUL
IP/Host: 127.0.0.1, Port 23
No experimend mode

Version 1.3.5 in /opt/iobroker/node_modules/iobroker.cul, node: v14.19.1, js-controller: 4.0.23

Is there any other info I can provide?

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

________________________________
Von: Ingo Fischer ***@***.***>
Gesendet: Monday, May 2, 2022 10:09:52 AM
An: ioBroker/ioBroker.cul ***@***.***>
Cc: Achim Mühlberger ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.cul] Problems with S300TH sensor address 0 (Issue #74)


Pleas eprovide more details , your settings and a proper debug log. Thank you.

**Comment by Apollon77** [comment]
Ok, now I got it ... please try GitHub version

**Comment by Apollon77** [comment]
Released now too
